### ISSUE TITLE
"cloudconvert / cloudconvert-laravel" is not compatible with php 8.1

### ISSUE THREAD

**Issue by ShubhamJadavSj** [cloudconvert/cloudconvert-laravel#13]
I have tried to install this package in laravel 9 with php 8.1

I am getting error while installation. Is there any chance of support being extended?

This is the error I am getting:

 Problem 1
    - cloudconvert/cloudconvert-laravel 1.1.2 requires cloudconvert/cloudconvert-php ^3.1.0 -> satisfiable by cloudconvert/cloudconvert-php[3.1.0, ..., 3.3.0].
    - cloudconvert/cloudconvert-laravel 1.1.0 requires php ^7.1 -> your php version (8.1.6) does not satisfy that requirement.
    - cloudconvert/cloudconvert-php 3.1.0 requires php ^7.1 -> your php version (8.1.6) does not satisfy that requirement.
    - cloudconvert/cloudconvert-laravel 1.1.1 requires illuminate/container ~5.8.0|^6.0|^7.0|^8.0 -> found illuminate/container[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - cloudconvert/cloudconvert-php[3.2.0, ..., 3.3.0] require php-http/client-implementation ^1.0 || ^2.0 -> could not be found in any version, but the following packages provide it:
      - symfony/http-client Provides powerful methods to fetch HTTP resources synchronously or asynchronously
      - php-http/guzzle6-adapter Guzzle 6 HTTP Adapter
      - symfony/symfony The Symfony PHP framework
      - php-http/curl-client PSR-18 and HTTPlug Async client with cURL
      - php-http/guzzle7-adapter Guzzle 7 HTTP Adapter
      - kriswallsmith/buzz Lightweight HTTP client
      - php-http/mock-client Mock HTTP client
      - php-http/socket-client Socket client for PHP-HTTP
      - php-http/guzzle5-adapter Guzzle 5 HTTP Adapter
      - voku/httpful A Readable, Chainable, REST friendly, PHP HTTP Client
      - php-http/react-adapter React HTTP Adapter
      - jorge-matricali/http-client A wrapper of libcurl that implements PSR-7 HTTP message interface.
      - code-tool/curl-client cURL client
      - juststeveking/http-slim A slim psr compliant http client to provide better interoperability.
      - code-tool/socket-client Socket client for PHP-HTTP
      - php-http/buzz-adapter Buzz HTTP Adapter
      - php-http/cakephp-adapter Cake adapter for PHP-HTTP
      - windwalker/http Windwalker Http package
      - swisnl/php-http-fixture-client Fixture client for PHP-HTTP
      - windwalker/framework The next generation PHP framework.
      ... and 35 more.
      Consider requiring one of these to satisfy the php-http/client-implementation requirement.
    - Root composer.json requires cloudconvert/cloudconvert-laravel ^1.1 -> satisfiable by cloudconvert/cloudconvert-laravel[1.1.0, 1.1.1, 1.1.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require cloudconvert/cloudconvert-laravel:*" to figure out if any version is installable, or "composer require cloudconvert/cloudconvert-laravel:^2.1" if you know which you need.

**Comment by josiasmontag** [comment]
It is compatible with PHP 8.1. You do not have any HTTP client installed, see:

> - cloudconvert/cloudconvert-php[3.2.0, ..., 3.3.0] require php-http/client-implementation ^1.0 || ^2.0 -> could not be found in any version, but the following packages provide it:
