### ISSUE TITLE
Laravel 9 / Guzzle

### ISSUE THREAD

**Issue by mw7147** [cloudconvert/cloudconvert-laravel#15]
This is from a fresh install of Laravel 9/php 8.1 with Guzzle

  Problem 1
    - cloudconvert/cloudconvert-laravel 1.1.2 requires cloudconvert/cloudconvert-php ^3.1.0 -> satisfiable by cloudconvert/cloudconvert-php[3.1.0, ..., 3.3.0].
    - cloudconvert/cloudconvert-laravel 1.1.0 requires php ^7.1 -> your php version (8.1.10) does not satisfy that requirement.
    - cloudconvert/cloudconvert-php 3.1.0 requires php ^7.1 -> your php version (8.1.10) does not satisfy that requirement.
    - cloudconvert/cloudconvert-laravel 1.1.1 requires illuminate/container ~5.8.0|^6.0|^7.0|^8.0 -> found illuminate/container[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - cloudconvert/cloudconvert-php[3.2.0, ..., 3.3.0] require php-http/client-implementation ^1.0 || ^2.0 -> could not be found in any version, but the following packages provide it:
      - symfony/http-client Provides powerful methods to fetch HTTP resources synchronously or asynchronously
      - php-http/guzzle6-adapter Guzzle 6 HTTP Adapter
      - symfony/symfony The Symfony PHP framework
      - php-http/curl-client PSR-18 and HTTPlug Async client with cURL
      - php-http/guzzle7-adapter Guzzle 7 HTTP Adapter
      - kriswallsmith/buzz Lightweight HTTP client
      - php-http/mock-client Mock HTTP client
      - php-http/socket-client Socket client for PHP-HTTP
      - php-http/guzzle5-adapter Guzzle 5 HTTP Adapter
      - voku/httpful A Readable, Chainable, REST friendly, PHP HTTP Client
      - php-http/react-adapter React HTTP Adapter
      - jorge-matricali/http-client A wrapper of libcurl that implements PSR-7 HTTP message interface.
      - juststeveking/http-slim A slim psr compliant http client to provide better interoperability.
      - code-tool/curl-client cURL client
      - php-http/buzz-adapter Buzz HTTP Adapter
      - windwalker/http Windwalker Http package
      - code-tool/socket-client Socket client for PHP-HTTP
      - prestashop/module-lib-guzzle-adapter Plug modules to the Guzzle client available on a running shop
      - php-http/cakephp-adapter Cake adapter for PHP-HTTP
      - mushroomcloud/guzzle6-adapter Guzzle 6 HTTP Adapter
      ... and 36 more.
      Consider requiring one of these to satisfy the php-http/client-implementation requirement.
    - Root composer.json requires cloudconvert/cloudconvert-laravel ^1.1 -> satisfiable by cloudconvert/cloudconvert-laravel[1.1.0, 1.1.1, 1.1.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by josiasmontag** [comment]
You need to have a HTTP client installed beforehand.
For example:
``
composer require php-http/guzzle7-adapter
``
