### ISSUE TITLE
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead

### ISSUE THREAD

**Issue by Tamrael** [cloudconvert/cloudconvert-laravel#18]
Installing cloudconvert/cloudconvert-laravel results in installing an abandoned package.

`Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead`

are there plans to update this package?

**Comment by josiasmontag** [comment]
The CloudConvert PHP SDK has been updated, version 3.4.0 solves this.
