### ISSUE TITLE
Upload file example

### ISSUE THREAD

**Issue by marekmez** [cloudconvert/cloudconvert-laravel#2]
Hi, would you be able to include example of  using **upload** method?  I am trying to upload file to CC and always having response "CloudConvert\Exceptions\HttpClientException  : Invalid data."

This is my code:
```
$job = (new Job())->setTag('test')
       ->addTask((new Task('import/upload', 'upload-my-file')));
                    
CloudConvert::jobs()->create($job);

$uploadTask = $job->getTasks()->name('upload-my-file')[0];

CloudConvert::tasks()->upload($uploadTask, Storage::get($path));
```

This is CC respose in Dashboard:
"ERROR UPLOAD_FAILED Upload failed: no files to process"

Thank you for any help.

Marek

**Comment by josiasmontag** [comment]
Which method call exactly is throwing the exception? CloudConvert::tasks()->upload()?

**Comment by marekmez** [comment]
Yes it is **CloudConvert::tasks()->upload();**

Method `create()` successfully registers task.

**Comment by josiasmontag** [comment]
I am not sure what `Storage::get()` returns. Does it work with `fopen()`?

**Comment by marekmez** [comment]
I will try `fopen()`. But becase this is Laravel extension it woulbe be good if it works with [Laravel - File Storage](https://laravel.com/docs/7.x/filesystem#retrieving-files)

**Comment by josiasmontag** [comment]
The `upload()` method needs a stream. The `Storage::get()` returns the file content directly.
This should work though (untested):

```php
$stream = Storage::disk('local')->getDriver()->readStream($fileName);
CloudConvert::tasks()->upload($uploadTask, $stream);
```

**Comment by marekmez** [comment]
Thanks, it seems to be giving right stream. Unfortunately, I am having this error now. It is triggered in `CloudConvert::tasks()->upload($uploadTask, $stream);` line. Job with tasks is created successfuly, but upload fails.

```
InvalidArgumentException  : First argument to Stream::create() must be a string, resource or StreamInterface.

  at ...\vendor\nyholm\psr7\src\Stream.php:87 
```

**Comment by itsdakmar** [comment]
Hello @marekmez, I had the same issue as yours. Have you found any solution?

**Comment by marekmez** [comment]
Hi @itsdakmar,

I had to use **import/url** method. At the moment I have temporarly made some file publicly available, once they are converted I move them back to where they were before. It is not quite a nice solution, but till `upload() method` is buggy I cannot do anything else.

**Comment by itsdakmar** [comment]
@marekmez do you mind share your code with me? thanks

**Comment by josiasmontag** [comment]
What is the issue with this solution? @marekmez 
https://github.com/cloudconvert/cloudconvert-laravel/issues/2#issuecomment-596801991

**Comment by marekmez** [comment]
To make it clear. `upload() method` throws an error based on your advice to use `readStream()`. This is still current issue in Laravel 6 (I have not tested v7).

```
InvalidArgumentException  : First argument to Stream::create() must be a string, resource or StreamInterface.
  at ...\vendor\nyholm\psr7\src\Stream.php:87
```

**Comment by marekmez** [comment]
@itsdakmar to make it work I had to use **import/url** insted of **import/upload**, steps are well documented in here https://github.com/cloudconvert/cloudconvert-laravel#usage

Important is to make your file available via url link. File should in **/storage/app/public/** folder. Than you can send link to CloudConvert. To make your folder public you should run `php artisan storage:link`.

Your link can be than like: **http::/your.app/storage/testfile.pdf**

**Comment by josiasmontag** [comment]
This works fine:
```php
CloudConvert::tasks()->upload($uploadTask, fopen(Storage::path($path), 'r'));
```
If there are issues with this way, please provide more details.

**Comment by brianakidd** [comment]
@josiasmontag I am having the same issue - here is my code:

```
$job = CloudConvert::jobs()->create(
            (new Job())
                ->setTag($this->id)
                ->addTask(new Task('import/upload', 'upload-file'))
                ->addTask(
                    (new Task('convert', 'convert-file'))
                        ->set('input', 'upload-file')
                        ->set('output_format', 'png')
                )
                ->addTask(
                    (new Task('export/url', 'export-file'))
                        ->set('input', 'convert-file')
                ));

        $uploadTask = $job->getTasks()->name('upload-file')[0];

        $inputStream = fopen($sourceFilePath, 'r');

        CloudConvert::tasks()->upload($uploadTask, $inputStream);
```

At ```CloudConvert::tasks()->upload($uploadTask, $inputStream);``` it throws error:

```
InvalidArgumentException : First argument to Stream::create() must be a string, resource or StreamInterface.
 .../vendor/nyholm/psr7/src/Stream.php:87
 .../vendor/nyholm/psr7/src/Factory/HttplugFactory.php:29
 .../vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php:320
 .../vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php:90
 .../vendor/cloudconvert/cloudconvert-php/src/Transport/HttpTransport.php:189
 .../vendor/cloudconvert/cloudconvert-php/src/Resources/TasksResource.php:111
 .../app/DocumentProcessing/Converters/CloudConvertConverter.php:52
```

I have done all of the obvious stuff such as making sure $sourceFilePath is a valid path to a document.  I guess I will have to resort to putting the file on s3 but this isn't ideal.

**Comment by josiasmontag** [comment]
This is really odd because [this](https://github.com/cloudconvert/cloudconvert-php/blob/master/tests/Integration/JobTest.php#L52) integration test just works fine.

I really would like to figure out why this is not working for some users. Can you debug if `$inputStream` is a valid resource object?

**Comment by brianakidd** [comment]
I've converted over to using s3 but will do this tomorrow so we can troubleshoot.  I did check that before I started looking at this issue on Github but I'll do it again tomorrow. Thanks.

**Comment by brianakidd** [comment]
@josiasmontag Unfortunately, I'm not going to have time to switch back to using the file upload but I can tell you that when I was debugging yesterday, I saw that the tasks or task collection was getting passed as the "body" to Stream::create() ```.../vendor/nyholm/psr7/src/Stream.php:87``` but I couldn't determine exactly where that was originating from.

**Comment by josiasmontag** [comment]
Fixed by https://github.com/cloudconvert/cloudconvert-php/commit/f34eca1b047be018425e4407d25d6d61719201b6 / cloudconvert-php `3.0.6`
