### ISSUE TITLE
Don't install cloudconvert-laravel on laravel/framework v5.6.39

### ISSUE THREAD

**Issue by itsdeo** [cloudconvert/cloudconvert-laravel#4]
Hi There,

I am getting below error while installing cloudconvert-laravel using "composer require cloudconvert/cloudconvert-laravel". 

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: don't install cloudconvert/cloudconvert-laravel 1.0.2
    - Conclusion: don't install cloudconvert/cloudconvert-laravel 1.0.1
    - Conclusion: remove laravel/framework v5.6.39
    - Installation request for cloudconvert/cloudconvert-laravel ^1.0 -> satisfiable by cloudconvert/cloudconvert-laravel[1.0.0, 1.0.1, 1.0.2].
    - Conclusion: don't install laravel/framework v5.6.39

Is there any package for laravel 5.6.39? 

Please help me on this.

Thank you!

**Comment by josiasmontag** [comment]
This SDK requires Laravel >= 5.8. 
Laravel 5.6 is not maintained any more, consider upgrading.

**Comment by rahul97480** [comment]
php artisan vendor:publish --provider="CloudConvert\Laravel\Providers\CloudConvertServiceProvider"
 says Unable to locate publishable resources.
