### ISSUE TITLE
Upload creates invalid stream from form parameters

### ISSUE THREAD

**Issue by harmenjanssen** [cloudconvert/cloudconvert-laravel#5]
Following the examples, this code produces the error: `"First argument to Stream::create() must be a string, resource or StreamInterface." on line 87 of /var/www/html/vendor/nyholm/psr7/src/Stream.php`

```php
        $job = (new Job())
            ->addTask(new Task('import/upload', 'upload-my-file'))
            ->addTask(
                (new Task('convert', 'convert-my-file'))
                    ->set('input', 'upload-my-file')
                    ->set('output_format', 'html')
            )
            ->addTask(
                (new Task('export/url', 'export-my-file'))
                    ->set('input', 'convert-my-file')
            );

        CloudConvert::jobs()->create($job);

        $uploadTask = $job->getTasks()->name('upload-my-file')[0];
        $inputStream = fopen($this->sourcePath, 'r');

        CloudConvert::tasks()->upload($uploadTask, $inputStream);

        CloudConvert::jobs()->wait($job);

        foreach ($job->getExportUrls() as $file) {
            $source = $cloudconvert->getHttpTransport()->download($file->url)->detach();
            exit($source);
        }
```

After some source diving, I've found the cause to be these lines in the HTTPTransport: https://github.com/cloudconvert/cloudconvert-php/blob/master/src/Transport/HttpTransport.php#L187-L189

Through `addResource`, it's trying to create streams from the entries in this array:

```
[
  "expires" => 1599583876
  "max_file_count" => 1
  "max_file_size" => 10000000000
  "x_delete_after" => 84600
  "redirect" => "https://api.cloudconvert.com/v2/upload/redirect/xxx"
  "signature" => "xxx"
]
```

Is there anything I can do to circumvent this?

**Comment by josiasmontag** [comment]
Related #2 

Can you please check if this patch would solve the issue?

Replace line [188 of HttpTransport.php](https://github.com/cloudconvert/cloudconvert-php/blob/8d99d1ab3f0516f8cbcd4e41fef24376812e3548/src/Transport/HttpTransport.php#L188) with:
```php
$builder->addResource($parameter, strval($value));
```

**Comment by harmenjanssen** [comment]
You're fast! 

Yes. That fixes it. Is there a way for me to fix this without changing 3rd party source code?

**Comment by josiasmontag** [comment]
I will push a patch for this.

**Comment by harmenjanssen** [comment]
Awesome! Thanks very much.

**Comment by josiasmontag** [comment]
Fixed by https://github.com/cloudconvert/cloudconvert-php/commit/f34eca1b047be018425e4407d25d6d61719201b6 / cloudconvert-php `3.0.6`

**Comment by harmenjanssen** [comment]
Thank you for a lightning fast response!
