### ISSUE TITLE
cloudconvert/cloudconvert-laravel 1.1.0 requires cloudconvert/cloudconvert-php ^3.1.0 -> satisfiable by cloudconvert/cloudconvert-php[3.1.0, 3.2.0, 3.2.1]

### ISSUE THREAD

**Issue by pradeepdeveloper143** [cloudconvert/cloudconvert-laravel#9]
Hello,

I am getting issue while installing this package on my laravel application.

My PHP version 7.4.x

Problem 1
    - cloudconvert/cloudconvert-laravel 1.1.0 requires cloudconvert/cloudconvert-php ^3.1.0 -> satisfiable by cloudconvert/cloudconvert-php[3.1.0, 3.2.0, 3.2.1].
    - cloudconvert/cloudconvert-laravel 1.1.1 requires cloudconvert/cloudconvert-php ^3.1.0 -> satisfiable by cloudconvert/cloudconvert-php[3.1.0, 3.2.0, 3.2.1].
    - cloudconvert/cloudconvert-php 3.2.1 requires php-http/client-implementation ^1.0 || ^2.0 -> no matching package found.
    - cloudconvert/cloudconvert-php 3.2.0 requires php-http/client-implementation ^1.0 || ^2.0 -> no matching package found.
    - cloudconvert/cloudconvert-php 3.1.0 requires php-http/client-implementation ^1.0 || ^2.0 -> no matching package found.
    - Installation request for cloudconvert/cloudconvert-laravel ^1.1 -> satisfiable by cloudconvert/cloudconvert-laravel[1.1.0, 1.1.1].

**Comment by josiasmontag** [comment]
Please make sure you have a HTTP client (Guzzle) installed.

**Comment by pradeepdeveloper143** [comment]
Hello,

It's already there.

        "guzzlehttp/guzzle": "^7.3",

**Comment by pradeepdeveloper143** [comment]
This is my composer.json


{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "doctrine/dbal": "~2.3",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.3",
        "infyomlabs/adminlte-templates": "^2.0",
        "infyomlabs/laravel-generator": "8.0.x-dev",
        "ladumor/one-signal": "^0.3.4",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "laravel/ui": "3.0",
        "laravelcollective/html": "^6.2"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^0.0.5",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by emmylexo** [comment]
Having this same issue, @pradeepdeveloper143 have you found a solution to the problem?

**Comment by KWijkniet** [comment]
I ran into a very similar problem. I was able to fix it by requiring another package (from the list given by the error message) that provides the required php-http/client-implementation before requiring the cloudconvert/cloudconvert-laravel package.

I dont know why other packages are required for this package to work. If someone can explain this please do!
I hope that this issue will be resolved in the future and that this might also help other people.

My error message:
 ```
 Problem 1
    - cloudconvert/cloudconvert-laravel[1.1.0, ..., 1.1.1] require cloudconvert/cloudconvert-php ^3.1.0 -> satisfiable by cloudconvert/cloudconvert-php[3.1.0, 3.2.0, 3.2.1].
    - cloudconvert/cloudconvert-php[3.1.0, ..., 3.2.1] require php-http/client-implementation ^1.0 || ^2.0 -> could not be found in any version, but the following packages provide it:
      - symfony/http-client Provides powerful methods to fetch HTTP resources synchronously or asynchronously
      - php-http/guzzle6-adapter Guzzle 6 HTTP Adapter
      - symfony/symfony The Symfony PHP framework
      - php-http/curl-client PSR-18 and HTTPlug Async client with cURL
      - kriswallsmith/buzz Lightweight HTTP client
      - php-http/guzzle7-adapter Guzzle 7 HTTP Adapter
      - php-http/mock-client Mock HTTP client
      - php-http/socket-client Socket client for PHP-HTTP
      - php-http/guzzle5-adapter Guzzle 5 HTTP Adapter
      - voku/httpful A Readable, Chainable, REST friendly, PHP HTTP Client
      - jorge-matricali/http-client A wrapper of libcurl that implements PSR-7 HTTP message interface.
      - php-http/buzz-adapter Buzz HTTP Adapter
      - code-tool/curl-client cURL client
      - php-http/cakephp-adapter Cake adapter for PHP-HTTP
      - windwalker/http Windwalker Http package
      - swisnl/php-http-fixture-client Fixture client for PHP-HTTP
      - windwalker/framework The next generation PHP framework.
      - betalabs/guzzle6-adapter Guzzle 6 HTTP Adapter
      - juststeveking/http-slim A slim psr compliant http client to provide better interoperability.
      - php-http/react-adapter React HTTP Adapter
      ... and 31 more.
      Consider requiring one of these to satisfy the php-http/client-implementation requirement.
    - Root composer.json requires cloudconvert/cloudconvert-laravel ^1.1 -> satisfiable by cloudconvert/cloudconvert-laravel[1.1.0, 1.1.1].
    - cloudconvert/cloudconvert-laravel is locked to version 1.1.1 and an update of this package was not requested.
```
